# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

 ActiveRecord::Base.establish_connection
    ActiveRecord::Base.connection.tables.each do |table|

      # SQLite
        ActiveRecord::Base.connection.execute("DELETE FROM #{table}") unless table == "schema_migrations"
        ActiveRecord::Base.connection.execute("DELETE FROM sqlite_sequence where name='#{table}'")


    end
    ActiveRecord::Base.connection.execute("VACUUM")



User.create(first_name: 'John', last_name: 'Doe', email: 'john@doe.com')
User.create(first_name: 'Jane', last_name: 'Doe', email: 'jane@doe.com')
User.create(first_name: 'Foo', last_name: 'Bar', email: 'foo@bar.com')

ResourceType.create(resource_type: 'Video')
ResourceType.create(resource_type: 'pdf')
ResourceType.create(resource_type: 'Website')

Licence.create(licence: 'MIT', description: 'Lorem ipsum')
Licence.create(licence: 'CC', description: 'Lorem ipsum')

t = Tag.create(tag: 'Biology')
t2 = Tag.create(tag: 'Science')
t3 = Tag.create(tag: 'Webb')
t4 = Tag.create(tag: 'Funny')


r =Resource.create(user_id: 1, resource_type_id: 3, licence_id: 1, title: "Resurs 1", desciption: "Bacon ipsum dolor sit amet kevin fatback pastrami pork loin bacon porchetta short loin pork ball tip turkey turducken jerky salami. Shankle hamburger biltong meatball ham hock. Doner pastrami pig beef. Bresaola short ribs pork chop doner shankle. Bresaola prosciutto pork, shoulder pancetta short ribs fatback sirloin beef venison short loin meatloaf. Ball tip shankle ground round rump sirloin leberkas kevin.", url: "http://www.joelstahre.com")
r2 =Resource.create(user_id: 1, resource_type_id: 2, licence_id: 1, title: "Resurs 2", desciption: "Pig fatback pork loin, strip steak pork chop kevin bresaola shank. Brisket tenderloin drumstick shankle pork loin landjaeger capicola boudin bresaola. Frankfurter turkey meatball tri-tip beef ribs jowl, kevin swine salami leberkas shankle brisket hamburger pork chop. Ball tip ham hock beef, capicola spare ribs pork loin short loin pig. Short loin spare ribs capicola, kevin bresaola sausage prosciutto kielbasa biltong pancetta cow turducken venison. Corned beef pancetta ham hock kielbasa landjaeger swine doner brisket jowl sausage chuck beef ribs tail.", url: "http://www.joelstahre.com")
r3 =Resource.create(user_id: 2, resource_type_id: 1, licence_id: 2, title: "Resurs 3", desciption: "Cow t-bone tri-tip pancetta tenderloin. Pork belly tri-tip sirloin drumstick, chuck venison shankle. Pork belly pork brisket, turducken shoulder ribeye porchetta tri-tip leberkas jerky. Pork belly kielbasa turkey t-bone chuck flank ham hock tongue pig.", url: "http://www.joelstahre.com")
r4 =Resource.create(user_id: 2, resource_type_id: 2, licence_id: 1, title: "Resurs 4", desciption: "Rump ham hock beef t-bone, sausage doner kielbasa frankfurter ribeye biltong pig corned beef prosciutto. Drumstick landjaeger prosciutto, pork chop ham hock sausage tenderloin beef ribs short loin sirloin boudin. Ribeye shankle landjaeger short ribs, filet mignon flank andouille rump pastrami. Rump ribeye tri-tip, meatloaf bacon sirloin boudin. Ham turkey strip steak, shank short loin frankfurter pig pork kielbasa short ribs pancetta rump tongue prosciutto ball tip.", url: "http://www.joelstahre.com")
r5 =Resource.create(user_id: 3, resource_type_id: 3, licence_id: 2, title: "Resurs 5", desciption: "Drumstick fatback pork jerky, turducken venison beef ribs pork belly tail swine tenderloin t-bone brisket. Pancetta bresaola brisket, capicola sirloin ham frankfurter shoulder beef ribs beef. Ribeye beef meatball, pork belly ham tail pig fatback bacon leberkas prosciutto cow. Rump fatback chuck ball tip. Boudin pork loin porchetta, sausage spare ribs rump swine cow filet mignon beef ribs prosciutto kielbasa bacon doner. Pancetta landjaeger short loin ball tip bresaola biltong.", url: "http://www.joelstahre.com")
r6 =Resource.create(user_id: 3, resource_type_id: 1, licence_id: 1, title: "Resurs 6", desciption: "Bacon ipsum dolor sit amet kevin fatback pastrami pork loin bacon porchetta short loin pork ball tip turkey turducken jerky salami. Shankle hamburger biltong meatball ham hock. Doner pastrami pig beef. Bresaola short ribs pork chop doner shankle. Bresaola prosciutto pork, shoulder pancetta short ribs fatback sirloin beef venison short loin meatloaf. Ball tip shankle ground round rump sirloin leberkas kevin.", url: "http://www.joelstahre.com")

r7 =Resource.create(user_id: 1, resource_type_id: 3, licence_id: 1, title: "Resurs 7", desciption: "Bacon ipsum dolor sit amet kevin fatback pastrami pork loin bacon porchetta short loin pork ball tip turkey turducken jerky salami. Shankle hamburger biltong meatball ham hock. Doner pastrami pig beef. Bresaola short ribs pork chop doner shankle. Bresaola prosciutto pork, shoulder pancetta short ribs fatback sirloin beef venison short loin meatloaf. Ball tip shankle ground round rump sirloin leberkas kevin.", url: "http://www.joelstahre.com")
r8 =Resource.create(user_id: 1, resource_type_id: 2, licence_id: 1, title: "Resurs 8", desciption: "Pig fatback pork loin, strip steak pork chop kevin bresaola shank. Brisket tenderloin drumstick shankle pork loin landjaeger capicola boudin bresaola. Frankfurter turkey meatball tri-tip beef ribs jowl, kevin swine salami leberkas shankle brisket hamburger pork chop. Ball tip ham hock beef, capicola spare ribs pork loin short loin pig. Short loin spare ribs capicola, kevin bresaola sausage prosciutto kielbasa biltong pancetta cow turducken venison. Corned beef pancetta ham hock kielbasa landjaeger swine doner brisket jowl sausage chuck beef ribs tail.", url: "http://www.joelstahre.com")
r9 =Resource.create(user_id: 2, resource_type_id: 1, licence_id: 2, title: "Resurs 9", desciption: "Cow t-bone tri-tip pancetta tenderloin. Pork belly tri-tip sirloin drumstick, chuck venison shankle. Pork belly pork brisket, turducken shoulder ribeye porchetta tri-tip leberkas jerky. Pork belly kielbasa turkey t-bone chuck flank ham hock tongue pig.", url: "http://www.joelstahre.com")
r10 =Resource.create(user_id: 2, resource_type_id: 2, licence_id: 1, title: "Resurs 10", desciption: "Rump ham hock beef t-bone, sausage doner kielbasa frankfurter ribeye biltong pig corned beef prosciutto. Drumstick landjaeger prosciutto, pork chop ham hock sausage tenderloin beef ribs short loin sirloin boudin. Ribeye shankle landjaeger short ribs, filet mignon flank andouille rump pastrami. Rump ribeye tri-tip, meatloaf bacon sirloin boudin. Ham turkey strip steak, shank short loin frankfurter pig pork kielbasa short ribs pancetta rump tongue prosciutto ball tip.", url: "http://www.joelstahre.com")
r11 =Resource.create(user_id: 3, resource_type_id: 3, licence_id: 2, title: "Resurs 11", desciption: "Drumstick fatback pork jerky, turducken venison beef ribs pork belly tail swine tenderloin t-bone brisket. Pancetta bresaola brisket, capicola sirloin ham frankfurter shoulder beef ribs beef. Ribeye beef meatball, pork belly ham tail pig fatback bacon leberkas prosciutto cow. Rump fatback chuck ball tip. Boudin pork loin porchetta, sausage spare ribs rump swine cow filet mignon beef ribs prosciutto kielbasa bacon doner. Pancetta landjaeger short loin ball tip bresaola biltong.", url: "http://www.joelstahre.com")
r12 =Resource.create(user_id: 3, resource_type_id: 1, licence_id: 1, title: "Resurs 12", desciption: "Bacon ipsum dolor sit amet kevin fatback pastrami pork loin bacon porchetta short loin pork ball tip turkey turducken jerky salami. Shankle hamburger biltong meatball ham hock. Doner pastrami pig beef. Bresaola short ribs pork chop doner shankle. Bresaola prosciutto pork, shoulder pancetta short ribs fatback sirloin beef venison short loin meatloaf. Ball tip shankle ground round rump sirloin leberkas kevin.", url: "http://www.joelstahre.com")

r13 =Resource.create(user_id: 1, resource_type_id: 3, licence_id: 1, title: "Resurs 13", desciption: "Bacon ipsum dolor sit amet kevin fatback pastrami pork loin bacon porchetta short loin pork ball tip turkey turducken jerky salami. Shankle hamburger biltong meatball ham hock. Doner pastrami pig beef. Bresaola short ribs pork chop doner shankle. Bresaola prosciutto pork, shoulder pancetta short ribs fatback sirloin beef venison short loin meatloaf. Ball tip shankle ground round rump sirloin leberkas kevin.", url: "http://www.joelstahre.com")
r14 =Resource.create(user_id: 1, resource_type_id: 2, licence_id: 1, title: "Resurs 14", desciption: "Pig fatback pork loin, strip steak pork chop kevin bresaola shank. Brisket tenderloin drumstick shankle pork loin landjaeger capicola boudin bresaola. Frankfurter turkey meatball tri-tip beef ribs jowl, kevin swine salami leberkas shankle brisket hamburger pork chop. Ball tip ham hock beef, capicola spare ribs pork loin short loin pig. Short loin spare ribs capicola, kevin bresaola sausage prosciutto kielbasa biltong pancetta cow turducken venison. Corned beef pancetta ham hock kielbasa landjaeger swine doner brisket jowl sausage chuck beef ribs tail.", url: "http://www.joelstahre.com")
r15 =Resource.create(user_id: 2, resource_type_id: 1, licence_id: 2, title: "Resurs 15", desciption: "Cow t-bone tri-tip pancetta tenderloin. Pork belly tri-tip sirloin drumstick, chuck venison shankle. Pork belly pork brisket, turducken shoulder ribeye porchetta tri-tip leberkas jerky. Pork belly kielbasa turkey t-bone chuck flank ham hock tongue pig.", url: "http://www.joelstahre.com")
r16 =Resource.create(user_id: 2, resource_type_id: 2, licence_id: 1, title: "Resurs 16", desciption: "Rump ham hock beef t-bone, sausage doner kielbasa frankfurter ribeye biltong pig corned beef prosciutto. Drumstick landjaeger prosciutto, pork chop ham hock sausage tenderloin beef ribs short loin sirloin boudin. Ribeye shankle landjaeger short ribs, filet mignon flank andouille rump pastrami. Rump ribeye tri-tip, meatloaf bacon sirloin boudin. Ham turkey strip steak, shank short loin frankfurter pig pork kielbasa short ribs pancetta rump tongue prosciutto ball tip.", url: "http://www.joelstahre.com")
r17 =Resource.create(user_id: 3, resource_type_id: 3, licence_id: 2, title: "Resurs 17", desciption: "Drumstick fatback pork jerky, turducken venison beef ribs pork belly tail swine tenderloin t-bone brisket. Pancetta bresaola brisket, capicola sirloin ham frankfurter shoulder beef ribs beef. Ribeye beef meatball, pork belly ham tail pig fatback bacon leberkas prosciutto cow. Rump fatback chuck ball tip. Boudin pork loin porchetta, sausage spare ribs rump swine cow filet mignon beef ribs prosciutto kielbasa bacon doner. Pancetta landjaeger short loin ball tip bresaola biltong.", url: "http://www.joelstahre.com")
r18 =Resource.create(user_id: 3, resource_type_id: 1, licence_id: 1, title: "Resurs 18", desciption: "Bacon ipsum dolor sit amet kevin fatback pastrami pork loin bacon porchetta short loin pork ball tip turkey turducken jerky salami. Shankle hamburger biltong meatball ham hock. Doner pastrami pig beef. Bresaola short ribs pork chop doner shankle. Bresaola prosciutto pork, shoulder pancetta short ribs fatback sirloin beef venison short loin meatloaf. Ball tip shankle ground round rump sirloin leberkas kevin.", url: "http://www.joelstahre.com")

r19 =Resource.create(user_id: 1, resource_type_id: 3, licence_id: 1, title: "Resurs 19", desciption: "Bacon ipsum dolor sit amet kevin fatback pastrami pork loin bacon porchetta short loin pork ball tip turkey turducken jerky salami. Shankle hamburger biltong meatball ham hock. Doner pastrami pig beef. Bresaola short ribs pork chop doner shankle. Bresaola prosciutto pork, shoulder pancetta short ribs fatback sirloin beef venison short loin meatloaf. Ball tip shankle ground round rump sirloin leberkas kevin.", url: "http://www.joelstahre.com")
r20 =Resource.create(user_id: 1, resource_type_id: 2, licence_id: 1, title: "Resurs 20", desciption: "Pig fatback pork loin, strip steak pork chop kevin bresaola shank. Brisket tenderloin drumstick shankle pork loin landjaeger capicola boudin bresaola. Frankfurter turkey meatball tri-tip beef ribs jowl, kevin swine salami leberkas shankle brisket hamburger pork chop. Ball tip ham hock beef, capicola spare ribs pork loin short loin pig. Short loin spare ribs capicola, kevin bresaola sausage prosciutto kielbasa biltong pancetta cow turducken venison. Corned beef pancetta ham hock kielbasa landjaeger swine doner brisket jowl sausage chuck beef ribs tail.", url: "http://www.joelstahre.com")
r21 =Resource.create(user_id: 2, resource_type_id: 1, licence_id: 2, title: "Resurs 21", desciption: "Cow t-bone tri-tip pancetta tenderloin. Pork belly tri-tip sirloin drumstick, chuck venison shankle. Pork belly pork brisket, turducken shoulder ribeye porchetta tri-tip leberkas jerky. Pork belly kielbasa turkey t-bone chuck flank ham hock tongue pig.", url: "http://www.joelstahre.com")
r22 =Resource.create(user_id: 2, resource_type_id: 2, licence_id: 1, title: "Resurs 22", desciption: "Rump ham hock beef t-bone, sausage doner kielbasa frankfurter ribeye biltong pig corned beef prosciutto. Drumstick landjaeger prosciutto, pork chop ham hock sausage tenderloin beef ribs short loin sirloin boudin. Ribeye shankle landjaeger short ribs, filet mignon flank andouille rump pastrami. Rump ribeye tri-tip, meatloaf bacon sirloin boudin. Ham turkey strip steak, shank short loin frankfurter pig pork kielbasa short ribs pancetta rump tongue prosciutto ball tip.", url: "http://www.joelstahre.com")
r23 =Resource.create(user_id: 3, resource_type_id: 3, licence_id: 2, title: "Resurs 23", desciption: "Drumstick fatback pork jerky, turducken venison beef ribs pork belly tail swine tenderloin t-bone brisket. Pancetta bresaola brisket, capicola sirloin ham frankfurter shoulder beef ribs beef. Ribeye beef meatball, pork belly ham tail pig fatback bacon leberkas prosciutto cow. Rump fatback chuck ball tip. Boudin pork loin porchetta, sausage spare ribs rump swine cow filet mignon beef ribs prosciutto kielbasa bacon doner. Pancetta landjaeger short loin ball tip bresaola biltong.", url: "http://www.joelstahre.com")
r24 =Resource.create(user_id: 3, resource_type_id: 1, licence_id: 1, title: "Resurs 24", desciption: "Bacon ipsum dolor sit amet kevin fatback pastrami pork loin bacon porchetta short loin pork ball tip turkey turducken jerky salami. Shankle hamburger biltong meatball ham hock. Doner pastrami pig beef. Bresaola short ribs pork chop doner shankle. Bresaola prosciutto pork, shoulder pancetta short ribs fatback sirloin beef venison short loin meatloaf. Ball tip shankle ground round rump sirloin leberkas kevin.", url: "http://www.joelstahre.com")

r25 =Resource.create(user_id: 1, resource_type_id: 3, licence_id: 1, title: "Resurs 25", desciption: "Bacon ipsum dolor sit amet kevin fatback pastrami pork loin bacon porchetta short loin pork ball tip turkey turducken jerky salami. Shankle hamburger biltong meatball ham hock. Doner pastrami pig beef. Bresaola short ribs pork chop doner shankle. Bresaola prosciutto pork, shoulder pancetta short ribs fatback sirloin beef venison short loin meatloaf. Ball tip shankle ground round rump sirloin leberkas kevin.", url: "http://www.joelstahre.com")
r26 =Resource.create(user_id: 1, resource_type_id: 2, licence_id: 1, title: "Resurs 26", desciption: "Pig fatback pork loin, strip steak pork chop kevin bresaola shank. Brisket tenderloin drumstick shankle pork loin landjaeger capicola boudin bresaola. Frankfurter turkey meatball tri-tip beef ribs jowl, kevin swine salami leberkas shankle brisket hamburger pork chop. Ball tip ham hock beef, capicola spare ribs pork loin short loin pig. Short loin spare ribs capicola, kevin bresaola sausage prosciutto kielbasa biltong pancetta cow turducken venison. Corned beef pancetta ham hock kielbasa landjaeger swine doner brisket jowl sausage chuck beef ribs tail.", url: "http://www.joelstahre.com")
r27 =Resource.create(user_id: 2, resource_type_id: 1, licence_id: 2, title: "Resurs 27", desciption: "Cow t-bone tri-tip pancetta tenderloin. Pork belly tri-tip sirloin drumstick, chuck venison shankle. Pork belly pork brisket, turducken shoulder ribeye porchetta tri-tip leberkas jerky. Pork belly kielbasa turkey t-bone chuck flank ham hock tongue pig.", url: "http://www.joelstahre.com")
r28 =Resource.create(user_id: 2, resource_type_id: 2, licence_id: 1, title: "Resurs 28", desciption: "Rump ham hock beef t-bone, sausage doner kielbasa frankfurter ribeye biltong pig corned beef prosciutto. Drumstick landjaeger prosciutto, pork chop ham hock sausage tenderloin beef ribs short loin sirloin boudin. Ribeye shankle landjaeger short ribs, filet mignon flank andouille rump pastrami. Rump ribeye tri-tip, meatloaf bacon sirloin boudin. Ham turkey strip steak, shank short loin frankfurter pig pork kielbasa short ribs pancetta rump tongue prosciutto ball tip.", url: "http://www.joelstahre.com")
r29 =Resource.create(user_id: 3, resource_type_id: 3, licence_id: 2, title: "Resurs 29", desciption: "Drumstick fatback pork jerky, turducken venison beef ribs pork belly tail swine tenderloin t-bone brisket. Pancetta bresaola brisket, capicola sirloin ham frankfurter shoulder beef ribs beef. Ribeye beef meatball, pork belly ham tail pig fatback bacon leberkas prosciutto cow. Rump fatback chuck ball tip. Boudin pork loin porchetta, sausage spare ribs rump swine cow filet mignon beef ribs prosciutto kielbasa bacon doner. Pancetta landjaeger short loin ball tip bresaola biltong.", url: "http://www.joelstahre.com")
r30 =Resource.create(user_id: 3, resource_type_id: 1, licence_id: 1, title: "Resurs 30", desciption: "Bacon ipsum dolor sit amet kevin fatback pastrami pork loin bacon porchetta short loin pork ball tip turkey turducken jerky salami. Shankle hamburger biltong meatball ham hock. Doner pastrami pig beef. Bresaola short ribs pork chop doner shankle. Bresaola prosciutto pork, shoulder pancetta short ribs fatback sirloin beef venison short loin meatloaf. Ball tip shankle ground round rump sirloin leberkas kevin.", url: "http://www.joelstahre.com")

r31 =Resource.create(user_id: 1, resource_type_id: 3, licence_id: 1, title: "Resurs 31", desciption: "Bacon ipsum dolor sit amet kevin fatback pastrami pork loin bacon porchetta short loin pork ball tip turkey turducken jerky salami. Shankle hamburger biltong meatball ham hock. Doner pastrami pig beef. Bresaola short ribs pork chop doner shankle. Bresaola prosciutto pork, shoulder pancetta short ribs fatback sirloin beef venison short loin meatloaf. Ball tip shankle ground round rump sirloin leberkas kevin.", url: "http://www.joelstahre.com")
r32 =Resource.create(user_id: 1, resource_type_id: 2, licence_id: 1, title: "Resurs 32", desciption: "Pig fatback pork loin, strip steak pork chop kevin bresaola shank. Brisket tenderloin drumstick shankle pork loin landjaeger capicola boudin bresaola. Frankfurter turkey meatball tri-tip beef ribs jowl, kevin swine salami leberkas shankle brisket hamburger pork chop. Ball tip ham hock beef, capicola spare ribs pork loin short loin pig. Short loin spare ribs capicola, kevin bresaola sausage prosciutto kielbasa biltong pancetta cow turducken venison. Corned beef pancetta ham hock kielbasa landjaeger swine doner brisket jowl sausage chuck beef ribs tail.", url: "http://www.joelstahre.com")
r33 =Resource.create(user_id: 2, resource_type_id: 1, licence_id: 2, title: "Resurs 33", desciption: "Cow t-bone tri-tip pancetta tenderloin. Pork belly tri-tip sirloin drumstick, chuck venison shankle. Pork belly pork brisket, turducken shoulder ribeye porchetta tri-tip leberkas jerky. Pork belly kielbasa turkey t-bone chuck flank ham hock tongue pig.", url: "http://www.joelstahre.com")
r34 =Resource.create(user_id: 2, resource_type_id: 2, licence_id: 1, title: "Resurs 34", desciption: "Rump ham hock beef t-bone, sausage doner kielbasa frankfurter ribeye biltong pig corned beef prosciutto. Drumstick landjaeger prosciutto, pork chop ham hock sausage tenderloin beef ribs short loin sirloin boudin. Ribeye shankle landjaeger short ribs, filet mignon flank andouille rump pastrami. Rump ribeye tri-tip, meatloaf bacon sirloin boudin. Ham turkey strip steak, shank short loin frankfurter pig pork kielbasa short ribs pancetta rump tongue prosciutto ball tip.", url: "http://www.joelstahre.com")
r35 =Resource.create(user_id: 3, resource_type_id: 3, licence_id: 2, title: "Resurs 35", desciption: "Drumstick fatback pork jerky, turducken venison beef ribs pork belly tail swine tenderloin t-bone brisket. Pancetta bresaola brisket, capicola sirloin ham frankfurter shoulder beef ribs beef. Ribeye beef meatball, pork belly ham tail pig fatback bacon leberkas prosciutto cow. Rump fatback chuck ball tip. Boudin pork loin porchetta, sausage spare ribs rump swine cow filet mignon beef ribs prosciutto kielbasa bacon doner. Pancetta landjaeger short loin ball tip bresaola biltong.", url: "http://www.joelstahre.com")
r36 =Resource.create(user_id: 3, resource_type_id: 1, licence_id: 1, title: "Resurs 36", desciption: "Bacon ipsum dolor sit amet kevin fatback pastrami pork loin bacon porchetta short loin pork ball tip turkey turducken jerky salami. Shankle hamburger biltong meatball ham hock. Doner pastrami pig beef. Bresaola short ribs pork chop doner shankle. Bresaola prosciutto pork, shoulder pancetta short ribs fatback sirloin beef venison short loin meatloaf. Ball tip shankle ground round rump sirloin leberkas kevin.", url: "http://www.joelstahre.com")

r.tags << t
r2.tags << t3
r2.tags << t3
r3.tags << t2
r4.tags << t2
r5.tags << t3
r6.tags << t4

Admin.create(first_name: 'admin', last_name: 'admin', admin_email: 'admin@admin.se', username: 'admin', password: 'password', password_confirmation: 'password')